version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/new_chatapp
hooks:
  BeforeInstall:
    - location: shellScript/before_installation.sh
      timeout: 500
      runas: root
  AfterInstall:
    - location: shellScript/after_installation.sh
      timeout: 800
      runas: root
